### ISSUE TITLE
NullPointerException in OWLXMLWriter

### ISSUE THREAD

**Issue by andreas-steigmiller** [ignazio1977/owllink-owlapi#1]
Hi Ignazio,

thank you very much for updating the owllink-owlapi adapter. We also tried to update it to the OWL API version 4/5, but since I’m not really familiar with the OWL API, I probably wrote and copied a lot of odd and sub-optimal code (cf. branch owlapi5 of https://github.com/andreas-steigmiller/owllink-owlapi-adapter). I tested your update of the owllink-owlapi adapter with the following test

```
import java.net.URL;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.*;
import org.semanticweb.owlapi.owllink.*;
import org.semanticweb.owlapi.reasoner.OWLReasoner;


public class ClassSatisfiabilityTest01 {

	public static void main(String[] args) {
		
		try {
			// create a test ontology
			OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
			OWLOntology ontology = manager.createOntology(IRI.create("http://test.de/"));
			OWLDataFactory dfactory = manager.getOWLDataFactory();
			OWLClass A = dfactory.getOWLClass(IRI.create("http://test.de/#A"));
			OWLClass B = dfactory.getOWLClass(IRI.create("http://test.de/#B"));
			OWLAxiom a = dfactory.getOWLSubClassOfAxiom(A, B);
			manager.addAxiom(ontology, a);
			
			// configure the server end-point
			URL url = new URL("http://127.0.0.1:8081");
			OWLlinkReasonerConfiguration reasonerConfiguration =
				new OWLlinkReasonerConfiguration(url);
			OWLlinkHTTPXMLReasonerFactory factory = new OWLlinkHTTPXMLReasonerFactory();
		 	OWLReasoner reasoner =
				factory.createNonBufferingReasoner(ontology, reasonerConfiguration);			
			
			System.out.println("Satisfiability of class " + A.toString() +": " + 
				reasoner.isSatisfiable(A));			
			
			// adding additional axioms to our test ontology to make class A unsatisfiable 
			OWLAxiom b = dfactory.getOWLSubClassOfAxiom(A, manager.getOWLDataFactory()
				.getOWLNothing());
			manager.addAxiom(ontology, b);

			System.out.println("After ontology changes, satisfiability of class " + 
				A.toString() +": " + reasoner.isSatisfiable(A));
			
		} catch (Exception e) {		
			e.printStackTrace();
		}
	}

}

```

but it currently produces the following null pointer exception:

```
org.semanticweb.owlapi.owllink.OWLlinkReasonerRuntimeException
	at org.semanticweb.owlapi.owllink.HTTPSessionImpl.performRequests(HTTPSessionImpl.java:222)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.performRequests(OWLlinkHTTPXMLReasoner.java:472)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.performRequest(OWLlinkHTTPXMLReasoner.java:476)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.createDefaultKB(OWLlinkHTTPXMLReasoner.java:460)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasoner.<init>(OWLlinkHTTPXMLReasoner.java:66)
	at org.semanticweb.owlapi.owllink.OWLlinkHTTPXMLReasonerFactory.createNonBufferingReasoner(OWLlinkHTTPXMLReasonerFactory.java:55)
	at ClassSatisfiabilityTest01.main(ClassSatisfiabilityTest01.java:35)
Caused by: java.lang.NullPointerException
	at org.semanticweb.owlapi.owlxml.renderer.OWLXMLWriter.<init>(OWLXMLWriter.java:79)
	at org.semanticweb.owlapi.owllink.renderer.OWLlinkXMLWriter.<init>(OWLlinkXMLWriter.java:76)
	at org.semanticweb.owlapi.owllink.renderer.OWLlinkXMLRenderer.render(OWLlinkXMLRenderer.java:68)
	at org.semanticweb.owlapi.owllink.HTTPSessionImpl.performRequests(HTTPSessionImpl.java:142)
	... 6 more
```

In particular, the ontology given to the OWLXMLWriter must not be null. In our update, we passed a (new) ontology object through a lot of method calls/constructors to have it in the OWLXMLWriter, which was a little bit painful, too. (As OWLlink server, I used Konclude, e.g., with the command line `./Konclude owllinkserver -p 8081`, but the exception is thrown before the owllink-owlapi adapter communicates with Konclude).

Unfortunately, I also cannot recommend our update since at least some queries for the owllink server are not working (and, as mentioned, some code is probably odd/sub-optimal). In the next days, I will try to have a closer look at the differences of our updates, but I think we should continue yours due to your experience with the OWL API. 

I’m not really sure whether Protege 5.* already switched to version 5 of the OWL API. As long as this is not the case, it would be beneficial to have some easy to maintain compatibility with OWL API 4 (as well as for OWL API 4 reasoners). But on the other hand, our update to the OWL API version 4 seems to work as protege plugin, so I think a focus on OWL API 5 for the owllink-owlapi adapter should be fine.

Best, Andreas

**Comment by ignazio1977** [comment]
Thank you, yes the error was reported in https://github.com/owlcs/owlapi/issues/793 as well. I've gotten as far as compiling with OWLAPI 5, but not yet started the adapter at all, so I expect a couple more of these gremlins to pop up.

Protege 5 is still using OWLAPI 4 - moving OWLAPI major versions is quite a big task for Protege, given the number of independently developed plugins that need to be included to keep users satisfied.

My changes so far have been simply dropping the classes that were copies of old OWLAPI code and replace them with the most recent OWL/XML parser I could easily transplant. The most recent parser doesn't fit conveniently, given that it was refactored to be smaller and only visible at package level - unfortunately this means that parser bugs are not easy to cherry pick across to OWLLink.

Speaking of that, I've been wondering - OWL/XML is chosen here to provide a format for the HTTP translation and so that the server side does not need to know the choices made by the client side in representing the axioms; however, as the project provides a server and a client side parser, if the server uses the OWLLink library for its parsing, the language used in transmission becomes irrelevant. So there's an option to write a client+server pair that uses another standard, and we could experiment with other options; for example, Matthew wrote a binary format for OWL - it is smaller in size and faster to parse than most text based formats, and it does not have some of the limitations of these languages (to name one, the QName limitations on some IRIs).

**Comment by andreas-steigmiller** [comment]
I totally agree that using the binary OWL format would be beneficial and speed up the communication quite a lot. One could use the HTTP content type header to specify which format is used and fall back to the HTTP/XML binding if the server reports an error. However, I don’t think that anyone has already specified how the OWLlink commands and queries should be represented in a binary format/binding, so there is still some work to do (in addition to the implementation in potentially several systems/libraries) :(

**Comment by ignazio1977** [comment]
Right, I'll put the format matter to the side for the moment. I can see there are binding specifications for three languages at the moment, but not much activity on other languages; however, the possibility of extra bindings is mentioned explicitly - which is a good thing.

**Comment by ignazio1977** [comment]
Fixed in the latest master. Debugging the new parser became too complex, so I went back to the original parser and copied the code that lived in OWLAPI 3 on which the old parser was relying. The licences are compatible (OWLAPI 3 is dual licensed under LGPL 3 or Apache).

Most unit tests pass with HermiT 1.43.517. The remaining failures seem due to HermiT bugs (one of them now fixed, a few more to investigate), so the connection seems to be healthy.
